"""init

Revision ID: 83e0ed1a8158
Revises: 
Create Date: 2026-05-10 08:50:01.556417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '83e0ed1a8158'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eval_results')
    op.drop_table('api_keys')
    op.drop_table('datasets')
    op.drop_table('versions')
    op.drop_table('eval_cases')
    op.drop_table('trace_steps')
    op.drop_table('reports')
    op.drop_table('eval_runs')
    op.drop_table('traces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trace_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('user_input', sa.TEXT(), nullable=False),
    sa.Column('prompt_version', sa.VARCHAR(length=255), nullable=True),
    sa.Column('model', sa.VARCHAR(length=255), nullable=True),
    sa.Column('retriever_version', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_latency_ms', sa.INTEGER(), nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['eval_cases.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.Column('prompt_version_id', sa.INTEGER(), nullable=True),
    sa.Column('model_version_id', sa.INTEGER(), nullable=True),
    sa.Column('retriever_version_id', sa.INTEGER(), nullable=True),
    sa.Column('agent_version_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_cases', sa.INTEGER(), nullable=False),
    sa.Column('passed_cases', sa.INTEGER(), nullable=False),
    sa.Column('failed_cases', sa.INTEGER(), nullable=False),
    sa.Column('avg_score', sa.FLOAT(), nullable=True),
    sa.Column('avg_latency_ms', sa.FLOAT(), nullable=True),
    sa.Column('avg_tokens', sa.FLOAT(), nullable=True),
    sa.Column('config_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_version_id'], ['versions.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['versions.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['versions.id'], ),
    sa.ForeignKeyConstraint(['retriever_version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('report_markdown', sa.TEXT(), nullable=False),
    sa.Column('summary_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trace_id_link', sa.VARCHAR(length=64), nullable=False),
    sa.Column('step_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('step_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('parent_step_id', sa.INTEGER(), nullable=True),
    sa.Column('input_json', sqlite.JSON(), nullable=True),
    sa.Column('output_json', sqlite.JSON(), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=False),
    sa.Column('tokens', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['parent_step_id'], ['trace_steps.id'], ),
    sa.ForeignKeyConstraint(['trace_id_link'], ['traces.trace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.Column('case_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('input', sa.TEXT(), nullable=False),
    sa.Column('reference_answer', sa.TEXT(), nullable=True),
    sa.Column('expected_tool', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expected_args', sqlite.JSON(), nullable=True),
    sa.Column('reference_context_ids', sqlite.JSON(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('config_json', sqlite.JSON(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('case_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=512), nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('default_model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('eval_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('actual_output', sa.TEXT(), nullable=True),
    sa.Column('actual_tool', sa.VARCHAR(length=255), nullable=True),
    sa.Column('actual_args', sqlite.JSON(), nullable=True),
    sa.Column('scores', sqlite.JSON(), nullable=True),
    sa.Column('failure_reason', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['eval_cases.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
